-- MySQL Script generated by MySQL Workbench
-- Thu May  5 04:42:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema E4CShop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `E4CShop` ;

-- -----------------------------------------------------
-- Schema E4CShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `E4CShop` DEFAULT CHARACTER SET utf8 ;
USE `E4CShop` ;

-- -----------------------------------------------------
-- Table `E4CShop`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `E4CShop`.`user` ;

CREATE TABLE IF NOT EXISTS `E4CShop`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `credits` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `modified_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userscol_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E4CShop`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `E4CShop`.`category` ;

CREATE TABLE IF NOT EXISTS `E4CShop`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `desc` LONGTEXT NULL,
  `count` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `modified_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E4CShop`.`collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `E4CShop`.`collection` ;

CREATE TABLE IF NOT EXISTS `E4CShop`.`collection` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `desc` LONGTEXT NULL,
  `creator_id` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `modified_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E4CShop`.`discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `E4CShop`.`discount` ;

CREATE TABLE IF NOT EXISTS `E4CShop`.`discount` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `desc` LONGTEXT NULL,
  `discount_percent` DECIMAL(3) NOT NULL,
  `modified_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E4CShop`.`artwork`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `E4CShop`.`artwork` ;

CREATE TABLE IF NOT EXISTS `E4CShop`.`artwork` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `desc` LONGTEXT NULL,
  `creator_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `collection_id` INT NULL,
  `price` INT NOT NULL,
  `discounts_id` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `modified_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `category_id`, `creator_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_artwork_user_idx` (`creator_id` ASC) VISIBLE,
  INDEX `fk_artwork_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_artwork_collection1_idx` (`collection_id` ASC) VISIBLE,
  INDEX `fk_artwork_discounts1_idx` (`discounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_artwork_user`
    FOREIGN KEY (`creator_id`)
    REFERENCES `E4CShop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `E4CShop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_collection1`
    FOREIGN KEY (`collection_id`)
    REFERENCES `E4CShop`.`collection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artwork_discounts1`
    FOREIGN KEY (`discounts_id`)
    REFERENCES `E4CShop`.`discount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E4CShop`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `E4CShop`.`transaction` ;

CREATE TABLE IF NOT EXISTS `E4CShop`.`transaction` (
  `id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `artwork_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `modified_at` DATETIME NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`, `buyer_id`, `artwork_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_transaction_user1_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `fk_transaction_artwork1_idx` (`artwork_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `E4CShop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_artwork1`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `E4CShop`.`artwork` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `E4CShop`.`filepath`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `E4CShop`.`filepath` ;

CREATE TABLE IF NOT EXISTS `E4CShop`.`filepath` (
  `artwork_id` INT NOT NULL,
  `original_path` VARCHAR(80) NOT NULL,
  `watermarked_path` VARCHAR(80) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `modified_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `deleted_at` DATETIME NULL,
  UNIQUE INDEX `original_path_UNIQUE` (`original_path` ASC) VISIBLE,
  UNIQUE INDEX `watermarked_path_UNIQUE` (`watermarked_path` ASC) VISIBLE,
  PRIMARY KEY (`artwork_id`),
  CONSTRAINT `fk_filepath_artwork1`
    FOREIGN KEY (`artwork_id`)
    REFERENCES `E4CShop`.`artwork` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

